name: PR deploy

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust application
        run: cargo build --release

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure VM
        env:
          AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Copy application to Azure VM
          az vm run-command invoke \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_VM_NAME \
            --command-id RunShellScript \
            --scripts "mkdir -p /home/$AZURE_VM_USERNAME/app"

          az vm copy \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_VM_NAME \
            --source-local-path "./target/release/OnlineLLM" \
            --destination "/home/$AZURE_VM_USERNAME/app/OnlineLLM"

          # Execute commands on Azure VM
          az vm run-command invoke \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_VM_NAME \
            --command-id RunShellScript \
            --scripts "
              sudo mv /home/$AZURE_VM_USERNAME/app/OnlineLLM /usr/local/bin/OnlineLLM
              sudo chown $AZURE_VM_USERNAME:$AZURE_VM_USERNAME /usr/local/bin/OnlineLLM
              sudo chmod 755 /usr/local/bin/OnlineLLM
              
              # Set environment variable
              echo 'export OPENAI_API_KEY=$OPENAI_API_KEY' | sudo tee -a /etc/environment
              
              # Run the application using nohup with output redirection
              sudo nohup /usr/local/bin/OnlineLLM > /dev/null 2>&1 &
              
              echo 'Application started'
            "

      - name: Logout from Azure
        run: |
          az logout
        if: always()
