name: PR deploy

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust application
        run: cargo build --release

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get VM public IP
        run: |
          AZURE_VM_IP=$(az vm show -d -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_VM_NAME }} --query publicIps -o tsv)
          echo "AZURE_VM_IP=$AZURE_VM_IP" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          echo "${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}" > vm_ssh_key
          chmod 600 vm_ssh_key

      - name: Copy binary to VM
        run: |
          scp -i vm_ssh_key -o StrictHostKeyChecking=no ./target/release/OnlineLLM ${{ secrets.AZURE_VM_USERNAME }}@${{ env.AZURE_VM_IP }}:/tmp/OnlineLLM

      - name: Deploy and start application
        env:
          AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          az vm run-command invoke \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_VM_NAME \
            --command-id RunShellScript \
            --scripts "
              # Move the binary to the correct location and set permissions
              sudo mv /tmp/OnlineLLM /usr/local/bin/OnlineLLM
              sudo chown $AZURE_VM_USERNAME:$AZURE_VM_USERNAME /usr/local/bin/OnlineLLM
              sudo chmod 755 /usr/local/bin/OnlineLLM
              
              # Set environment variable
              echo 'export OPENAI_API_KEY=$OPENAI_API_KEY' | sudo tee -a /etc/environment
              
              # Stop any existing instance of the application
              sudo pkill -f OnlineLLM || true
              
              # Run the application using nohup with output redirection
              sudo -u $AZURE_VM_USERNAME nohup /usr/local/bin/OnlineLLM > /dev/null 2>&1 &
              
              echo 'Application deployed and started'
            "

      - name: Logout from Azure
        run: az logout
        if: always()

