name: PR deploy

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust application
        run: cargo build --release

      - name: Deploy to EC2 and set environment variable
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Set up SSH key using ssh-agent
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          # Transfer application to EC2 instance using SCP
          scp -o StrictHostKeyChecking=no target/release/OnlineLLM ubuntu@$EC2_HOST:/home/ubuntu/

          # SSH into EC2 instance and execute commands
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST '
            # Move application to appropriate directory
            sudo mv /home/ubuntu/OnlineLLM /usr/local/bin/OnlineLLM
            sudo chown ubuntu:ubuntu /usr/local/bin/OnlineLLM
            sudo chmod 755 /usr/local/bin/OnlineLLM            

            # Run the application using nohup with output redirection
            sudo nohup /usr/local/bin/OnlineLLM > /dev/null 2>&1 &

            # Ensure the command completes
            echo "Application started"
          '
